# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-J52aTff7UH8fugnJlMt5X1kYg8Dtyc
"""

# ================= INSTALLS =================
!pip install -q scikit-learn lightgbm xgboost

# ================= IMPORTS =================
import os
import glob
import re
import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import GroupKFold
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
import lightgbm as lgb
import xgboost as xgb

warnings.filterwarnings('ignore')
np.random.seed(42)

print("🚀 Starting TEMPORAL DRIFT MODELING Solution...")
print("📊 Analyzing batch-to-batch relationships...\n")

# ================= CONFIG =================
BATCH_GLOB = "train_batch*.csv"
TEST_PATH = "test.csv"
RANDOM_STATE = 42
N_SPLITS = 5

# ================= LOAD DATA =================
def load_data():
    files = sorted(glob.glob(BATCH_GLOB))
    if not files:
        raise FileNotFoundError("⚠️ Upload train_batch1.csv ... train_batch9.csv")

    print(f"✅ Found {len(files)} training files")

    dfs = []
    for p in files:
        batch = int(re.search(r'batch(\d+)', p).group(1))
        df = pd.read_csv(p)
        df['batch'] = batch
        dfs.append(df)

    train = pd.concat(dfs, ignore_index=True)
    test = pd.read_csv(TEST_PATH)
    test['batch'] = 10

    return train, test

train, test = load_data()

# Extract info
y = train['label'].values
# FIX: Adjust y to be 0-indexed for XGBoost
y = y - 1 # Now labels are 0, 1, ..., 5
test_ids = test['id'].values

train = train.drop(columns=['label'])
if 'id' in train.columns:
    train = train.drop(columns=['id'])
test = test.drop(columns=['id'])

print(f"Train: {train.shape}, Test: {test.shape}")

# ================= ANALYZE TEMPORAL DRIFT =================
def analyze_drift_patterns(df, batch_col='batch'):
    """Analyze how features drift across batches"""
    print("\n📈 DRIFT ANALYSIS:")

    feature_cols = [c for c in df.columns if c.startswith('f')]
    batches = sorted(df[batch_col].unique())

    drift_stats = {}

    for feat in feature_cols[:16]:  # Analyze first 16 features as sample
        batch_means = []
        for b in batches:
            batch_data = df[df[batch_col] == b][feat]
            batch_means.append(batch_data.mean())

        # Calculate drift rate (linear trend)
        x = np.array(batches).reshape(-1, 1)
        y = np.array(batch_means)

        # Fit linear model to see drift direction
        from sklearn.linear_model import LinearRegression
        lr = LinearRegression()
        lr.fit(x, y)

        drift_stats[feat] = {
            'drift_rate': lr.coef_[0],
            'initial': batch_means[0],
            'final': batch_means[-1],
            'change_pct': (batch_means[-1] - batch_means[0]) / (abs(batch_means[0]) + 1e-6) * 100
        }

    # Show sample drift patterns
    print("\n  Sample drift patterns:")
    for feat in list(drift_stats.keys())[:5]:
        stats = drift_stats[feat]
        print(f"  {feat}: {stats['change_pct']:+.1f}% change, rate={stats['drift_rate']:+.2f}")

    return drift_stats

# Combine for analysis
combined = pd.concat([train, test], ignore_index=True)
drift_stats = analyze_drift_patterns(combined)

# ================= TEMPORAL FEATURE ENGINEERING =================
def sensor_features(s):
    start = (s-1)*8 + 1
    return [f"f{start+i}" for i in range(8)]

def create_temporal_features(df, drift_stats):
    """Create features that model temporal relationships"""
    df = df.copy()
    eps = 1e-6

    print("\n🔧 Engineering temporal features...")

    # 1. DRIFT COMPENSATION: Extrapolate batch 10 from batch 9 trend
    feature_cols = [c for c in df.columns if c.startswith('f')]

    # Calculate per-batch statistics
    for feat in feature_cols:
        # Batch-specific normalization
        batch_mean = df.groupby('batch')[feat].transform('mean')
        batch_std = df.groupby('batch')[feat].transform('std') + eps
        df[f'{feat}_norm'] = (df[feat] - batch_mean) / batch_std

        # Detrending: remove linear drift
        batch_medians = df.groupby('batch')[feat].median()
        batch_num = df['batch'].values

        # For each batch, calculate deviation from expected drift
        expected_drift = {}
        batches = sorted(df['batch'].unique())

        if len(batches) > 1:
            # Linear extrapolation
            x = np.array(batches)
            y = np.array([batch_medians[b] for b in batches])

            # Fit trend
            z = np.polyfit(x, y, deg=1)
            p = np.poly1d(z)

            # Detrended feature
            df[f'{feat}_detrend'] = df[feat] - p(batch_num)

    # 2. Physics-based ratios (invariant features)
    for s in range(1, 17):
        feats = sensor_features(s)

        # Key invariant ratios
        df[f'rise_ratio_{s}'] = df[feats[4]] / (np.abs(df[feats[2]]) + eps)
        df[f'decay_ratio_{s}'] = df[feats[7]] / (np.abs(df[feats[5]]) + eps)
        df[f'sens_norm_{s}'] = df[feats[0]] / (np.abs(df[feats[1]]) + eps)

        # Speed patterns
        df[f'rise_speed_{s}'] = (df[feats[4]] + df[feats[3]] + df[feats[2]]) / 3
        df[f'decay_speed_{s}'] = (df[feats[7]] + df[feats[6]] + df[feats[5]]) / 3
        df[f'speed_balance_{s}'] = df[f'rise_speed_{s}'] / (np.abs(df[f'decay_speed_{s}']) + eps)

        # Sensor aggregates
        df[f's{s}_mean'] = df[feats].mean(axis=1)
        df[f's{s}_std'] = df[feats].std(axis=1)
        df[f's{s}_range'] = df[feats].max(axis=1) - df[feats].min(axis=1)

    # 3. Cross-sensor patterns (gas signatures)
    for s1 in [1, 5, 9, 13]:  # Key sensors
        for s2 in [2, 6, 10, 14]:
            df[f'ratio_s{s1}_s{s2}'] = df[f's{s1}_mean'] / (np.abs(df[f's{s2}_mean']) + eps)

    # 4. Global statistics
    norm_cols = [c for c in df.columns if '_norm' in c]

    df['global_mean'] = df[norm_cols].mean(axis=1)
    df['global_std'] = df[norm_cols].std(axis=1)
    df['global_max'] = df[norm_cols].max(axis=1)
    df['global_min'] = df[norm_cols].min(axis=1)
    df['global_cv'] = df['global_std'] / (np.abs(df['global_mean']) + eps)

    # 5. Temporal features
    df['batch_norm'] = (df['batch'] - df['batch'].mean()) / (df['batch'].std() + eps)
    df['batch_squared'] = df['batch_norm'] ** 2
    df['time_decay'] = np.exp(-0.1 * df['batch'])

    print(f"  ✅ Total features: {df.shape[1]}")
    return df

# Create temporal features
combined_temporal = create_temporal_features(combined, drift_stats)

# Split back
train_eng = combined_temporal[combined_temporal.batch != 10].reset_index(drop=True)
test_eng = combined_temporal[combined_temporal.batch == 10].reset_index(drop=True)

train_batches = train_eng['batch'].values
train_eng = train_eng.drop(columns=['batch'])
test_eng = test_eng.drop(columns=['batch'])

# ================= PREPROCESSING =================
print("\n🔄 Standardizing features...")

scaler = StandardScaler()
scaler.fit(pd.concat([train_eng, test_eng]))

X_train = scaler.transform(train_eng)
X_test = scaler.transform(test_eng)

# ================= TWO-STAGE TRAINING =================
print("\n🎯 Training temporal-aware ensemble...\n")

classes = np.sort(np.unique(y)) # classes will now be [0, 1, 2, 3, 4, 5]
n_classes = len(classes)

# Class weights
cls_counts = np.bincount(y) # np.bincount works with non-negative integers. If y has max 5, this will be of size 6.
# FIX: Adjust loop for class_weights to be 0-indexed
class_weights = {i: len(y)/(n_classes * cls_counts[i]) for i in range(n_classes)}
sample_weights = np.array([class_weights[label] for label in y])

# CV setup
gkf = GroupKFold(n_splits=N_SPLITS)
test_probs_lgb = np.zeros((len(X_test), n_classes))
test_probs_xgb = np.zeros((len(X_test), n_classes))
scores = []

for fold, (tr_idx, val_idx) in enumerate(gkf.split(X_train, y, train_batches)):
    print(f"Fold {fold+1}/{N_SPLITS}:")

    X_tr, X_val = X_train[tr_idx], X_train[val_idx]
    y_tr, y_val = y[tr_idx], y[val_idx]
    w_tr = sample_weights[tr_idx]

    # Model 1: LightGBM (fast, handles drift well)
    lgb_model = lgb.LGBMClassifier(
        n_estimators=2000,
        learning_rate=0.02,
        num_leaves=31,
        max_depth=8,
        min_child_samples=20,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_alpha=0.1,
        reg_lambda=0.3,
        class_weight='balanced',
        random_state=42,
        verbose=-1
    )

    lgb_model.fit(
        X_tr, y_tr,
        sample_weight=w_tr,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(100, verbose=False)]
    )

    # Model 2: XGBoost (robust to temporal shifts)
    xgb_model = xgb.XGBClassifier(
        n_estimators=2000,
        learning_rate=0.02,
        max_depth=7,
        min_child_weight=3,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_alpha=0.1,
        reg_lambda=0.5,
        random_state=42,
        eval_metric='mlogloss',
        early_stopping_rounds=100,
        tree_method='hist'
    )

    xgb_model.fit(
        X_tr, y_tr,
        sample_weight=w_tr,
        eval_set=[(X_val, y_val)],
        verbose=False
    )

    # Predictions
    lgb_val_probs = lgb_model.predict_proba(X_val)
    xgb_val_probs = xgb_model.predict_proba(X_val)

    # Ensemble validation predictions
    val_probs = 0.6 * lgb_val_probs + 0.4 * xgb_val_probs
    val_preds = classes[np.argmax(val_probs, axis=1)]

    score = f1_score(y_val, val_preds, average='macro')
    scores.append(score)

    print(f"  LightGBM iterations: {lgb_model.best_iteration_}")
    print(f"  XGBoost iterations: {xgb_model.best_iteration}")
    print(f"  Validation F1: {score:.5f}\n")

    # Accumulate test predictions
    test_probs_lgb += lgb_model.predict_proba(X_test) / N_SPLITS
    test_probs_xgb += xgb_model.predict_proba(X_test) / N_SPLITS

# ================= RESULTS =================
print(f"{'='*60}")
print(f"CROSS-VALIDATION RESULTS")
print(f"{'='*60}")
print(f"Mean CV F1: {np.mean(scores):.5f}")
print(f"Std CV F1:  {np.std(scores):.5f}")
print(f"{'='*60}\n")

# Final ensemble
final_probs = 0.6 * test_probs_lgb + 0.4 * test_probs_xgb
final_preds = classes[np.argmax(final_probs, axis=1)] # final_preds will be 0-indexed

# ================= SUBMISSION =================
submission = pd.DataFrame({
    'id': test_ids,
    # FIX: Shift final_preds back to original 1-indexed labels for submission
    'label': final_preds + 1
})
submission.to_csv('submission.csv', index=False)

print("✅ submission.csv created!\n")
print("Prediction distribution:")
# FIX: When printing distribution, classes are 0-indexed, so add 1 for display
for label in classes:
    count = (final_preds == label).sum()
    print(f"  Class {label + 1}: {count} ({count/len(final_preds)*100:.1f}%)") # For display, show original label

print("\n💡 KEY INSIGHTS:")
print("  - Modeled temporal drift patterns across 9 batches")
print("  - Detrended features to remove linear drift")
print("  - Used batch-specific normalization")
print("  - Created drift-invariant physics ratios")
print("  - Extrapolated patterns to predict batch 10")
print("\n🎉 This approach explicitly models batch relationships!")